import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { NextProviders, ReactQueryProvider } from '@/app/providers'
import ThemeToggle from '@/components/ThemeSwitcher'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'RTG-FrontTesk',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='ko'>
      <body className={`min-h-screen`}>
        <ReactQueryProvider>
          <NextProviders>
            <header className={`flex justify-end p-2`}>
              <ThemeToggle />
            </header>
            {children}
          </NextProviders>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
