import type { Metadata } from 'next'
import './globals.css'
import { NextProviders, ReactQueryProvider } from '@/app/providers'
import ThemeToggle from '@/components/ThemeSwitcher'

export const metadata: Metadata = {
  title: 'RTG-FrontTesk',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='ko'>
      <body className={`min-h-screen`}>
        <ReactQueryProvider>
          <NextProviders>
            <header className={`flex justify-end p-2`}>
              <ThemeToggle />
            </header>
            {children}
          </NextProviders>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
